from model.motion_nepa import MotionNEPA, motionNEPA
from model.pose_transformer_vae import PoseTransformerVAE, poseTransformerVAE
from model.pose_transformer_vae_vel import PoseTransformerVAEVel, poseTransformerVAEVel
from model.pose_transformer_vae_nepa import PoseTransformerVAENEPA, poseTransformerVAENEPA
from model.pose_transformer_vae_nepa_cross import PoseTransformerVAENEPACross, poseTransformerVAENEPACross
from model.pose_transformer_vae_nepa_cross_linear import PoseTransformerVAENEPACrossLinear, poseTransformerVAENEPACrossLinear
from model.auxformer_xyz import AuxFormerXYZ, auxFormerXYZ
from model.auxformer_nepa_joint import AuxFormerNEPAJoint, auxFormerNEPAJoint
